Neos:
  Neos:
    modules:
      cloudflare:
        label: 'Cloudflare'
        controller: '\Neos\Neos\Controller\Module\ManagementController'
        description: 'Cloudflare'
        icon: 'fab fa-cloudflare'
        resource: 'Neos_Neos_Backend_Module_Management'
        submodules:
          proxyCacheManager:
            label: 'Proxy Cache Manager'
            controller: '\NeosRulez\Neos\Cloudflare\Controller\Module\ProxyCacheManagerController'
            description: 'Cloudflare Proxy Cache Manager'
            icon: 'fas fa-bolt'
            actions:
              index:
                label: 'Proxy Cache Manager'
                title: 'Proxy Cache Manager'
