Neos:
  ContentRepositoryRegistry:
    presets:
      'default':
        contentGraphProjection:
          catchUpHooks:
            'NeosRulez.Neos.Cloudflare:FlushProxyCache':
              factoryObjectName: NeosRulez\Neos\Cloudflare\ContentRepository\FlushProxyCacheCatchUpHookFactory
